CREATE DATABASE DUAN1
GO
USE DUAN1
GO

CREATE TABLE NhanVien(
    MaNV NVARCHAR(50) NOT NULL PRIMARY KEY,
    MatKhau NVARCHAR(50) NOT NULL,
    HoTen NVARCHAR(50) NOT NULL,
    VaiTro BIT NOT NULL,
);

CREATE TABLE ChuyenDe(
    MaCD NVARCHAR(50) NOT NULL PRIMARY KEY,
    TenCD NVARCHAR(50) NOT NULL,
    HocPhi FLOAT NOT NULL,
    ThoiLuong INT NOT NULL,
    Hinh NVARCHAR(50) NOT NULL,
    MoTa NVARCHAR(255) NOT NULL
);

CREATE TABLE KhoaHoc(
    MaKH INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    MaCD NVARCHAR(50) NOT NULL,
    HocPhi FLOAT NOT NULL,
    ThoiLuong INT NOT NULL,
    NgayKG DATE NOT NULL,
    GhiChu NVARCHAR(50) NOT NULL,
    MaNV NVARCHAR(50) NOT NULL,
    NgayTao DATE NOT NULL,
    CONSTRAINT FK_KhoaHoc_ChuyenDe FOREIGN KEY (MaCD) REFERENCES ChuyenDe(MaCD),
    CONSTRAINT FK_KhoaHoc_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE NguoiHoc(
    MaNH NVARCHAR(50) NOT NULL PRIMARY KEY,
    HoTen VARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh BIT NOT NULL,
    DienThoai NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) NOT NULL,
    GhiChu NVARCHAR(255) NOT NULL,
    MaNV NVARCHAR(50) NOT NULL,
    NgayDK DATE NOT NULL,
    CONSTRAINT FK_NguoiHoc_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE HocVien(
    MaHV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    MaKH INT NOT NULL,
    MaNH NVARCHAR(50) NOT NULL,
    Diem FLOAT NOT NULL,
    CONSTRAINT FK_HocVien_KhoaHoc FOREIGN KEY (MaKH) REFERENCES KhoaHoc(MaKH),
    CONSTRAINT FK_HocVien_NguoiHoc FOREIGN KEY (MaNH) REFERENCES NguoiHoc(MaNH),
);
